### ISSUE TITLE
createJSModules() removed on android

### ISSUE THREAD

**Issue by adi23arora** [dayitv89/react-native-quick-firebase#10]
For react-native version 0.47.2 onwards, `createJSModules` method used in Android module was removed and it is mentioned as a breaking change [here](https://github.com/facebook/react-native/releases/tag/v0.47.2).

So as to support react-native versions >= 0.47.2, the overriding method must be removed.

**Comment by dayitv89** [comment]
Thanks for reporting @adi23arora. Fixed now.
